---
# tasks file for hswong3i.mysql

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "present", repo: "ppa:ondrej/mysql-5.7" }
  tags: hswong3i.mysql

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "automysqlbackup" }
    - { state: "latest", name: "libdbd-mysql-perl" }
    - { state: "latest", name: "mysql-server" }
    - { state: "latest", name: "python-mysqldb" }
  notify: restart mysql
  tags: hswong3i.mysql

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/mysql/conf.d/mysql.cnf.j2", dest: "/etc/mysql/conf.d/mysql.cnf.j2",  owner: "root", group: "root", mode: "0644" }
    - { src: "etc/mysql/conf.d/mysqldump.cnf.j2", dest: "/etc/mysql/conf.d/mysqldump.cnf.j2",  owner: "root", group: "root", mode: "0644" }
    - { src: "etc/mysql/mysql.conf.d/mysqld.cnf.j2", dest: "/etc/mysql/mysql.conf.d/mysqld.cnf.j2",  owner: "root", group: "root", mode: "0644" }
    - { src: "etc/mysql/mysql.conf.d/mysqld_safe_syslog.cnf.j2", dest: "/etc/mysql/mysql.conf.d/mysqld_safe_syslog.cnf.j2",  owner: "root", group: "root", mode: "0644" }
  notify: restart mysql
  tags: hswong3i.mysql

- name: enable service
  service:
    name: "mysql"
    enabled: "yes"
  notify: restart mysql
  tags: hswong3i.mysql
