---
# tasks file for hswong3i.mysql

- name: apt-get install
  apt: name="{{ item }}" state=latest
  with_items:
    - mysql-server
    - python-mysqldb
  notify: restart mysql
  tags: hswong3i.mysql

- name: enable service
  service: name=mysql enabled=yes
  notify: restart mysql
  tags: hswong3i.mysql
